version: '3.8'

services:
  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kyx-api-quota-bridge:latest
    container_name: kyx-api-quota-bridge
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      # 应用配置
      - PORT=8080
      - DATABASE_PATH=/app/data/data.db

      # 从 .env 文件加载其他环境变量
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - JWT_SECRET=${JWT_SECRET}
      - CLAUDE_API_URL=${CLAUDE_API_URL:-https://api.anthropic.com}

      # OAuth 配置（如需要）
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      # 时区
      - TZ=Asia/Shanghai
    volumes:
      # 持久化数据库
      - ./data:/app/data
      # 如果需要自定义配置
      # - ./config.yaml:/app/config.yaml:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - "com.kyx-api-quota-bridge.description=KYX API Quota Bridge Service"
      - "com.kyx-api-quota-bridge.version=1.0.0"

networks:
  app-network:
    driver: bridge

volumes:
  # 如果需要使用 Docker volume 而不是 bind mount
  # app-data:
  #   driver: local
